### ISSUE TITLE
Should headers be saved by default in the `@metadata` field?

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-http#10]
I was looking at other plugins like the `logstash-input-elasticsearch`, this plugin save the `docinfo` values into the  `@metadata` field (the user can change the target), should we do the same for this plugin to be consistent?

**Comment by andrewvc** [comment]
:+1:

**Comment by ebuildy** [comment]
should be fixed by https://github.com/logstash-plugins/logstash-input-http/pull/68 isnit?

**Comment by jsvd** [comment]
solved by #68
