### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-http#123]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

**Comment by farrp** [comment]
The "host" field should be "host.name". 

The "headers" field in the document root contains many fields that have proper ECS locations:
"headers" => {
"http_version" => "HTTP/1.1",
"request_path" => "/HealthCheck",
"accept_encoding" => "gzip, compressed",
"http_accept" => nil,
"http_user_agent" => "ELB-HealthChecker/2.0",
"http_host" => "172.31.x.x:443",
"request_method" => "GET",
"connection" => "close",
"content_length" => "0"
}

**Comment by kaisecheng** [comment]
| Legacy  | ECS |
| ------------- | ------------- |
| http_version  | http.version  |
| http_user_agent | user_agent.original, user_agent.name, user_agent.version |
| http_host | host.ip, url.port |
| request_method | http.method |
| request_path  | url.path  |
| content_length | http.request.body.bytes |
| content_type | http.request.mime_type |
