### ISSUE TITLE
Plugin installed on elastic search directory

### ISSUE THREAD

**Issue by mrkaspa** [logstash-plugins/logstash-input-http#14]
After installing the plugin:
plugin install logstash-plugins/logstash-input-http --verbose
-> Installing logstash-plugins/logstash-input-http...
Trying https://github.com/logstash-plugins/logstash-input-http/archive/master.zip...
Downloading .......DONE
Installed logstash-plugins/logstash-input-http into /usr/local/var/lib/elasticsearch/plugins/logstash-input-http
Identified as a _site plugin, moving to _site structure ...
Installed logstash-plugins/logstash-input-http into /usr/local/var/lib/elasticsearch/plugins/logstash-input-http/_site

When I run the command the plugin isn't found:

logstash -f /Users/michelperez/code/go/src/github.com/mrkaspa/gologstash/logstash-simple.conf
The error reported is:
  Couldn't find any input plugin named 'http'. Are you sure this is correct? Trying to load the http input plugin resulted in this error: no such file to load -- logstash/inputs/http

**Comment by jordansissel** [comment]
@mrkaspa I think we may have mislead you on the documentation. the `bin/plugin` you ran is the one for Elasticsearch. You need to run the one for Logstash.

**Comment by mrkaspa** [comment]
I think the problem is with brew because elsatic & logstash have the same name for exec plugin so I only have one the elastic search

**Comment by jsvd** [comment]
this issue is unrelated this plugin,  it's more about logstash-core and namespacing of the binaries. closing
