### ISSUE TITLE
uninitialized constant LogStash::Inputs::Http::Base64

### ISSUE THREAD

**Issue by arabold** [logstash-plugins/logstash-input-http#17]
I'm using Logstash 1.5.3 and was trying a very simple Logstash configuration. However, when starting up Logstash throws an error: `uninitialized constant LogStash::Inputs::Http::Base64`.

Here's my config:
```
input {

  syslog {
    type => "syslog"
    port => 5544
    tags => []
    add_field => {
      "index" => "syslog"
    }
  }

  http {
    type => "http"
    port => 8080
    user => "logstash"
    password => "*******"
    tags => [ "webhook" ]
  }

}

# Add your filters here
filter {

}

output {
  # Trying to debug things? Enable the stdout output plugin
  stdout {
    codec => rubydebug
  }
}
```

What am I doing wrong here?

**Comment by suyograo** [comment]
Fixed via https://github.com/logstash-plugins/logstash-input-http/pull/18. Thanks @wiibaa
