### ISSUE TITLE
Fails to parse json

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-input-http#20]
I use http input and output to forward the logs from one system to another.

The output works fairly well (aside from an easy bug to fix). On the other hand, the input plugin doesn't seem to like the directive codec and doesn't parse the logs accordingly.

Client configuration:
```
        http {
               format => "json"
                http_method => "post"
                url => "http://10.0.0.1:8080/"
```

Server configuration:
```
        http {
                threads => 10
               codec => "json"
        }
```

I made a packet capture to see what's going wrong and I can see the json is encoded correctly (validated) and the request is correct but I get 400 Bad request every single time. When I look on the server, I can see messages like this:
```
2015-07-30 15:27:55 -0600: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2015-07-30 15:27:55 -0600: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:fd 2>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "CONTENT_TYPE"=>"text/plain", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.11.3", "GATEWAY_INTERFACE"=>"CGI/1.2", "REQUEST_METHOD"=>"POST"}
```

which seem to indicate that the input http doesn't take the codec into account when decoding. 

Disabling json on both sides fixes the issue.

**Comment by jsvd** [comment]
@ThomasdOtreppe strange..I just tried with logstash 1.5.3:

config:

```
input {
   http {
      threads => 10
      codec => "json"
   }
}
filter {
}
output { stdout { codec => rubydebug } }
```

And pushed a json formatted event using curl:

```
curl -XPUT 'http://127.0.0.1:8080/twitter/tweet/1' -d '{                                               
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}'
```

and on logstash side I got:

```
/tmp/logstash-1.5.3 % bin/logstash -f conf
Logstash startup completed
{
          "user" => "kimchy",
     "post_date" => "2009-11-15T14:12:12",
       "message" => "trying out Elasticsearch",
      "@version" => "1",
    "@timestamp" => "2015-07-31T15:30:29.001Z",
       "headers" => {
           "content_type" => "application/json",
         "request_method" => "PUT",
           "request_path" => "/twitter/tweet/1",
            "request_uri" => "/twitter/tweet/1",
           "http_version" => "HTTP/1.1",
        "http_user_agent" => "curl/7.37.1",
              "http_host" => "127.0.0.1:8080",
            "http_accept" => "*/*",
         "content_length" => "110"
    }
}
```

Can you maybe post the full HTTP request you made to logstash?

**Comment by ThomasdOtreppe** [comment]
Here what I got from a packet capture:

```
POST / HTTP/1.1
host: 10.167.0.1
connection: keep-alive
content-type: application/json
content-length: 348

{"clock":1438210669,"host":"collector-beta","@version":"1","@timestamp":"2015-07-29T22:57:49.316Z","type":"heartbeat","tags":["epoch"],"customer":{"name":"My company and  co","location":"Somewhere in USA, CA","branch":"","country":"USA","note":"Beta test","contact":{"name":"","email":"","phone":""}},"@uuid":"11208958-79a8-4e03-ace0-d9e48159cefa"}HTTP/1.1 400 Bad Request
```

Here is the capture file: http://demo.ovh.eu/en/00f029367008b13df39873c90a1a7424/

**Comment by jsvd** [comment]
My guess here is that the request is not being built with "\r\n" to split new lines but a single "\n". For example:

OK

```
% printf "HEAD / HTTP/1.0\r\n\r\n" |nc  127.0.0.1 8080
HTTP/1.0 200 OK
Content-Type: text/plain
Content-Length: 2
```

Not OK

```
% printf "HEAD / HTTP/1.0\n\n" |nc  127.0.0.1 8080
HTTP/1.1 400 Bad Request
```

**Comment by jsvd** [comment]
@ThomasdOtreppe can you confirm that the request is malformed, can I close this issue?

**Comment by ThomasdOtreppe** [comment]
Yes, the request is malformed but it shouldn't be closed because logstash output http plugin was used to generate the request and logstash http input was used to receive the data.

**Comment by jsvd** [comment]
Ahhh..I failed to understand that....strangely the http output sent by the output plugin has proper CRLF terminations, so I'm again not understanding why the request is malformed.
Digging deeper..

**Comment by jsvd** [comment]
Ah, I can see what's wrong..the config:

```
input {
  generator { count => 1 message => "hi" }
}
output {
  http {
    url => "http://localhost:3333"
    http_method => "post"
  }
}
```

Generated the following request:

```
POST  HTTP/1.1
host: localhost
connection: keep-alive
content-type: application/json
content-length: 117

{"message":"hi","@version":"1","@timestamp":"2015-08-11T17:23:50.482Z","host":"Joaos-MacBook-Pro.local","sequence":0}
```

Which is malformed due to lack of path in the POST line, should be something like `POST / HTTP/1.1`
I'm going to move this to logstash-plugins/logstash-output-http

**Comment by jsvd** [comment]
Which is the issue you have opened 12 days ago :) https://github.com/logstash-plugins/logstash-output-http/issues/14

**Comment by jsvd** [comment]
since logstash-plugins/logstash-output-http#14 has been fixed this is no longer an issue, it's possible to send from logstash-output-http to logstash-input-http :+1:
