### ISSUE TITLE
Use as tracking pixel

### ISSUE THREAD

**Issue by arabold** [logstash-plugins/logstash-input-http#21]
I think it would be super easy, yet super effective to enable use of this plugin as tracking pixel as well. Currently the plugin returns "OK" if someone sends data to it. If we extend it to support something like `response_type` with possible values such as `plain` (returning an empty page as of today) or `gif` (setting proper `Content-Type` header and returning a 1-pixel sized GIF image), this should do the trick. Any thoughts on this?

**Comment by jordansissel** [comment]
Agreed! This was a thought I had also. +1

**Comment by suyograo** [comment]
Fixed in #29
