### ISSUE TITLE
HTTP NOT WORK

### ISSUE THREAD

**Issue by w0www** [logstash-plugins/logstash-input-http#27]
When i put in my config 
  http {
    host => "https://openexchangerates.org/api/currencies.json"
  }

i get this error "The error reported is: \n  initialize: name or service not known"

help?

**Comment by jsvd** [comment]
This plugin works by opening a webserver and receiving requests. I believe you want to use the (logstash-input-http_poller)[https://github.com/logstash-plugins/logstash-input-http_poller], that works the other way: you specify a url and it polls the url every x seconds

**Comment by jsvd** [comment]
Closing this issue as http polling is out of scope for this plugin.

**Comment by w0www** [comment]
Yes, i need http_poller :) Thanks!!!
