### ISSUE TITLE
Get sender's IP from Nginx

### ISSUE THREAD

**Issue by Scratch-net** [logstash-plugins/logstash-input-http#36]
Hi there, referring to #22 I have nginx in front of logstash and my host is always 127.0.0.1. Is it possible to take host from header?

**Comment by jsvd** [comment]
I'm not sure I understand, but if you want to replace the host with a value from the header I'd suggest using a mutate filter

**Comment by Scratch-net** [comment]
Sorry, I've already fixed this long time ago via mutate/replace/remove_field
