### ISSUE TITLE
What do I need to do to configure this plugin after I have installed it?

### ISSUE THREAD

**Issue by BrianGilbert** [logstash-plugins/logstash-input-http#38]
I've been searching google and not having any luck finding how to set this up properly.

Some documentation would be greatly appreciated.

Thanks
Brian

**Comment by markwalkom** [comment]
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html is a start.

But please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions.  We reserve Github for confirmed bugs and feature requests :)
