### ISSUE TITLE
thread limit 

### ISSUE THREAD

**Issue by ageetha** [logstash-plugins/logstash-input-http#39]
Is there a limit on maximum number of threads for http input plugin? we have a http proxy server sending requests to logstash ( http input plugin) . 1000s of clients are expected to connect to logstash and how does maxclients of http server ( Apache) relate to threads in logstash http input plugin?

**Comment by wiibaa** [comment]
For info this plugin depends on Puma server
So from a quick googling I would says that settings **threads** in this plugin configuration is equivalent to MaxClients in httpd,  :
* https://github.com/puma/puma#thread-pool
* http://httpd.apache.org/docs/2.0/mod/mpm_common.html#maxclients
* https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#threads

**Comment by jsvd** [comment]
I believe this is answered, closing
