### ISSUE TITLE
Response status 200 when output not available

### ISSUE THREAD

**Issue by porcobravo** [logstash-plugins/logstash-input-http#48]
Hello,

Recently the server I was outputting logstash was down, but the http plugin kept returning status 200 to the client pushing events, resulting in a loss of data. I just wanted to discuss if it could be interesting to the plugin to return 200 only when the message has successfully passed through the output. This way it would allow clients to capture the error and retry.

If people still needs current behavior, one way to implement it could be adding a configuration option to choose which one is needed.

Thanks.

**Comment by jsvd** [comment]
I understand that problem, the limitation right now in logstash is the lack of end-to-end feedback/ack.
The semantics of such a thing aren't easily defined since an event received by the inputs can be split into many (1 to many) and joined again later (many to 1) in the filter section, so when you finally send the event to the output you might no longer have the identity of the event that was received in the input.

Also, waiting for a response from the output to return 200 in the input makes the data flow extremely slow, specially for outputs like elasticsearch, where events are grouped into a bulk to reduce RTT.

That said, in most scenarios logstash should retry sending data indefinitely and not drop received events.
Which outputs are you using? Can you post your configuration?

**Comment by porcobravo** [comment]
I see the problem now. A proper solution to this seems not easy.

I'm building a logstash infra as suggested in logstash help page (the last one, with shipper, queue, indexer parts).

I'm using Kafka as queue, and this config file belongs to the shipper part:
```
input {
    http {
        port => 5050
        host => "logshipper01"
        codec => json
    }
}

output {
    kafka {
        topic_id => "shipper"
        bootstrap_servers => "kafka01:9092"
    }
}

```

Everything was working ok, but for whatever reason, kafka server stopped working, the client kept pushing and got 200. The result was a loss of data because the client does not store events. Luckily for us it is currently a prototype, so the data loss was not a problem by itself.

**Comment by jsvd** [comment]
interesting...which version of logstash and the kafka output?
What normally should happen is that, when kafka server stops, then logstash will block trying to send data out, and stop accepting more data, so the client doing a PUT/POST would be blocked waiting for a response from logstash "forever", eventually timing out.

If this is not happening there might be a bug in the kafka output.

**Comment by porcobravo** [comment]
I'm using logstash 2.2.2 and kafka 2.11-0.9.0.0

I understand, the internal queue of logstash is full (can't flush data to kafka), so logstash can't acecpt new requests. The colleague that wrote the client didn't reported me any timeout request, only 200. I'll check kafka output about this issue.

Thank you very much for all the explanations.

PS: Is there any way to know which is the maximum message size accepted by the plugin? Is there a way to change it? If these questions are better posted in another place let me know.

**Comment by jsvd** [comment]
I suggest opening an issue in the kafka output plugin about potentially not exerting back pressure as expected. Post any logs showing errors if possible.

As for message size, you mean a single http POST?

**Comment by porcobravo** [comment]
Yes, I was referring size for each request.

**Comment by jsvd** [comment]
definitely smaller than the size you allocate for the logstash jvm :) other than that I have no concrete numbers.
If you're ok with the answers for this issue we can close it, if you still have issues please open another, or use discuss.elastic.co for broader, non-issue questions.

**Comment by porcobravo** [comment]
I believe we can close this one. Once I have confirmed some additional facts, I will open a new issue regarding request size.
Thanks again for all the explanations.
