### ISSUE TITLE
Publish to rubygems

### ISSUE THREAD

**Issue by angad** [logstash-plugins/logstash-input-http#5]
https://rubygems.org/search?utf8=%E2%9C%93&query=logstash-input-http

**Comment by xytis** [comment]
I needed this for production ^^

https://rubygems.org/gems/logstash-input-http

**Comment by jordansissel** [comment]
We hadn't published this yet because the plugin may not be ready for use. @xytis because you published this, we have no access to publish it further unless you set us as an owner on the rubygem.

**Comment by jordansissel** [comment]
Also, it's not required to _publish_ a gem in order to use it with Logstash, you can build it yourself and install it locally without needing to put it on rubygems.org. This is how we test bug fixes and do integration tests today, fyi.

**Comment by xytis** [comment]
I will set you as owner, I published it because it is easier to setup 'bin/plugin install name' than 'git clone > gem build > bin/plugin install path_to_gem' in automated builds.
