### ISSUE TITLE
verify_mode - "peer" vs. "force_peer"

### ISSUE THREAD

**Issue by simonclausen** [logstash-plugins/logstash-input-http#55]
I would like to raise a question about the behavior of the "verify_mode" setting.

I set "verify_mode" to "peer" expecting that it would check certificates: it does, but if I don't feel like presenting a certificate, I am free to proceed.

Is there a use case where one would check the validity of a client cert, and then let them in anyway, if none is presented?

If not, would it make sense to remove the "force_peer" option and make the functionality of "peer" equal to this?

Possible relevant PR and discussion:
- #37 
- b7506fe296016f210da03b6fc151bf64f88dec2a

**Comment by jsvd** [comment]
this should now be how it works:

```
  # By default the server doesn't do any client verification.
  #
  # `peer` will make the server ask the client to provide a certificate.
  # If the client provides a certificate, it will be validated.
  #
  # `force_peer` will make the server ask the client to provide a certificate.
  # If the client doesn't provide a certificate, the connection will be closed.
  #
  # This option needs to be used with `ssl_certificate_authorities` and a defined list of CAs.
  config :ssl_verify_mode, :validate => ["none", "peer", "force_peer"], :default => "none"
```
