### ISSUE TITLE
how to use logstash http plugin

### ISSUE THREAD

**Issue by tarun003** [logstash-plugins/logstash-input-http#62]
Hello Everyone ,
 I am using Restful api as an input to get data into Elastic search using logstash http plugin.For example we need to extract Walmart data using URL provided by walmart Rest api.As i am run this configuration file indeces is not created in output.Here i am attaching my configuration file
input {
  http {
       URI => "http://api.walmartlabs.com/v1/search?query=ipod&format=json&apiKey="
}
      }

output {  
stdout { codec => rubydebug }
    elasticsearch { 
	   action => "index"
       hosts => "127.0.0.1:9200"	   
       index => "Walmart labs "       
       workers => 1
	   document_type => "Walmart data"
       document_id => "%{id}"
    }
 }
 As i am new to use these tools i am not able to use http plugin properly and parameters need to passi input .Please guide me how to use it

**Comment by jsvd** [comment]
I believe you want to poll a rest endpoint for data, so you need to use the http_poller plugin and not the http input plugin. see more about usage in https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html
