### ISSUE TITLE
Does password field work on http input?

### ISSUE THREAD

**Issue by paul42** [logstash-plugins/logstash-input-http#63]
Latest version of logstash,
created logstash config:
```
input {
  http {
    host => "127.0.0.1"
    port => 5400
    id => "http_input"
    response_headers => {"Content-Type"=>"application/json"}
    codec => json
    password => "example"
  }
}

output {
    stdout{
     codec => rubydebug
    }
}
```
when I use Postman and set the basic auth header, it works, I see stdout output, but it still passes through when I remove the header and set it to noauth - it works when I change the password on auth as well. is there a test suite I can run to verify?

**Comment by charleshepner** [comment]
I assume you need to specify `username` in addition to `password` for basic auth to work.

**Comment by ebuildy** [comment]
@paul42 is it ok?

**Comment by jsvd** [comment]
I'm moving this to https://github.com/logstash-plugins/logstash-input-http/issues/88, since we should error out when only password is set without a username.
