### ISSUE TITLE
resource overload when backend (eg elastic) unavailable 

### ISSUE THREAD

**Issue by pputerla** [logstash-plugins/logstash-input-http#66]
in https://github.com/logstash-plugins/logstash-input-http/blob/master/lib/logstash/inputs/http.rb:144 
(for reference - commit https://github.com/logstash-plugins/logstash-input-http/commit/7fb9f850218190baecbdfb7f63c5f6dc71d47598)

we have:

```ruby
       body = req.delete("rack.input")
        @codecs.fetch(req["content_type"], @codec).decode(body.read) do |event|
          event.set("host", remote_host)
          event.set("headers", req)
          decorate(event)

#HERE:
          queue << event


        end
        ['200', @response_headers, ['ok']]
      rescue => e
        @logger.error(
          "unable to process event.", 
```

according to my investigation "queue" is a blocking queue

For example. If my elastic does not process some messages eg:

    [2017-06-12T09:52:00,488][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429

and we multiply it with dozens servers sending hundreds of http messages we have a situation when
a) logstash stops sending data to backend (that's expected and ok )
b) logstash by means of puma http server accept()'s every connection, and when client closes TCP session puma does not call close() method thuys leaving sockets in CLOSE_WAIT state + massive amount of block'ed waiting threads

**Comment by pputerla** [comment]
BTW sideeffect: when puma reaches max files limit it does not simply exit/crash whatever - insted it loops and floods system with repeated error message ;

I understand that puma issue should be fixed by the puma guys (https://github.com/puma/puma)
but can sb. help with the logstash issue here?

Personally I think the best thing would be to respond with HTTP 500 code as soon as possible. Cuirrently it just does not respond (of course: it's a blocked thread :)

**Comment by jonassteinberg1** [comment]
+1

**Comment by inversion** [comment]
+1

**Comment by jordansissel** [comment]
Please refrain from adding "+1" comments. It adds a lot of noise to the hundreds of emails I already get each day, and everyone subscribed to this repo wil receive your "+1" comment via email. 

We have no voting system. If an issue is impacting you, and you wish to participate, and your thoughts and concerns are not already voiced in the thread by someone else, I welcome comments with details on your use case, how you are impacted by this, how you measure this impact, etc.

I have deleted all "+1" comments at this time.

**Comment by inversion** [comment]
We have a large number of nodes posting data to this input plugin, and as described by the original post it creates huge numbers of socket and thread pairs when there is any downtime in the elasticsearch output, resulting in it needing to be restarted.

**Comment by jsvd** [comment]
PR #73 will allow setting the SO_BACKLOG, so we can reject new connections after the backlog is full

**Comment by jsvd** [comment]
Version 3.1.0 has been released using netty instead of puma. This implementation [limits the maximum of inflight events](https://github.com/logstash-plugins/logstash-input-http/blob/master/docs/index.asciidoc#max_pending_requests) and returns 429 when limits are reached.

> We have a large number of nodes posting data to this input plugin, and as described by the original post it creates huge numbers of socket and thread pairs when there is any downtime in the elasticsearch output, resulting in it needing to be restarted.

For a large number of nodes you'll still need to set your file decriptors accordingly as each connection uses one, but the threads are now pooled.

**Comment by jsvd** [comment]
closing this, please open a new issue if you're seeing unexpected backpressure behaviour with version >= 3.1.0
