### ISSUE TITLE
Add option to disable "ok" resonse 

### ISSUE THREAD

**Issue by jakommo** [logstash-plugins/logstash-input-http#67]
It seems like the "ok" response is [hardcoded](https://github.com/logstash-plugins/logstash-input-http/blob/master/lib/logstash/inputs/http.rb#L146).
I'm using a cronjob to send nmap data to the http input, similar to what is described in [this blog post](https://www.elastic.co/blog/using-nmap-logstash-to-gain-insight-into-your-network).
The issue with the `ok` response is that it causes an email from cron being generated, every time the job runs, which is annoying. 
I know that I can redirect the output, but I can imagine that there are other use cases where no response would be appreciated as well. 
Proposing to add an option to disable the response.

**Comment by ebuildy** [comment]
we could add an option to specify the response?

**Comment by Ronookkeli** [comment]
It would be useful if the response payload could be specified. Some Soap web service interfaces expect to receive Soap-message in the response payload when http 200 is responded, and do not accept the current response payload of 'ok'. Other thing, nice to have, would be able to respond http 202 Accepted with empty payload.

**Comment by jsvd** [comment]
adding a note here: setting `response_code => 204` (No Content) will not return a response body.

I'm closing this issue as the original goal of disabling `ok` responses is implemented, and adding https://github.com/logstash-plugins/logstash-input-http/issues/117 to track the configuration of the response_body string.
