### ISSUE TITLE
Customer would like the ability to specify ciphers and protocols allowed

### ISSUE THREAD

**Issue by e-mars** [logstash-plugins/logstash-input-http#71]
- Version: 5.6
- Operating System: CentOS 6.X

Customer is asking for ability to limit which ciphers can be used and which protocols.
similar to what is available in Filebeat with `cipher_suites` and `supported_protocols` options:
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-ssl.html

thanks.

**Comment by AndrewMcQuerry** [comment]
Hi @e-mars,  (I figured I'd jump in here and update this issue directly).

I've done some digging into this plugin to see exactly how the http port is opened/served.  I see that it's using the "puma" library, which I've also dug into.

From what I can tell, the protocols and cipher list are hard-coded within the Puma libraries, as shown below:

Inside the “MiniSSL.java” file, line 161
`String[] protocols =newString[] { "TLSv1", "TLSv1.1", "TLSv1.2"};`

And inside “mini_ssl.c” file, line 178
`SSL_CTX_set_cipher_list(ctx, "HIGH:!aNULL@STRENGTH");`


> Disclaimer: Since I'm not intimately familiar with these libraries, this information could be off-track.   Just hoping to provide some input to anyone who's able to take a quick look at this.


If the above is correct, and the Puma library offers no way to manipulate these values, what would be the alternative to being able to remove TLSv1/TLSv1.1 and certain ciphers from being enabled for this port?

**Comment by jordansissel** [comment]
@andrewvc Puma in JRuby doesn't use any C extensions, so the C code you looked at is not used in Logstash (JRuby).

We can make it work, even if it means patching Puma or changing what provides the http service.

**Comment by AndrewMcQuerry** [comment]
Thanks @jordansissel for clearing that up.

**Comment by AndrewMcQuerry** [comment]
Any idea what the source of the cipher suite is that is enabled for these ports?

**Comment by AndrewMcQuerry** [comment]
Hi all,
Can anyone share what the expected time frame is to decide which solution to go with and then how long it would take to have a patch for us to use?

We're looking into using a Proxy to open up the port facing the LAN, and then having it forward all traffic to the input http plugin assigned directly to a localhost port.  But we see this as a temporary work-around, thus the questions around what we can expect for a fix to make its way into the logstash plugin.


Thanks!

**Comment by jordansissel** [comment]
I have no estimate at this time.

**Comment by jsvd** [comment]
this will arrive with #73

**Comment by jsvd** [comment]
With version 3.1.0 this is now possible: [cipher_suites](https://github.com/logstash-plugins/logstash-input-http/blob/master/docs/index.asciidoc#plugins-inputs-http-cipher_suites) and [tls_max_version](https://github.com/logstash-plugins/logstash-input-http/blob/master/docs/index.asciidoc#plugins-inputs-http-tls_max_version) + [tls_min_version](https://github.com/logstash-plugins/logstash-input-http/blob/master/docs/index.asciidoc#plugins-inputs-http-tls_min_version)
