### ISSUE TITLE
logstash ouput to kafka and es, when kafka is down, logstash is blocked, stop output to es too

### ISSUE THREAD

**Issue by QinXiao2017** [logstash-plugins/logstash-input-http#72]
logstash.conf 

output {
	elasticsearch {
	hosts => "elasticsearch:9200"
	}

    if [logtype] == "delimitlog" {
        kafka {
                topic_id => "test"
                bootstrap_servers => "10.162.115.99:9092"
        }
    }
}

**Comment by QinXiao2017** [comment]
Is there any config to set logstash output to kafka asyn?

**Comment by QinXiao2017** [comment]
another question, if the kafka restart, logstash need restart too.
but, if es restart, logstash desn't need restart.
Is there any config? or any other reason?

**Comment by QinXiao2017** [comment]
any one can answer me, please.
Thanks so much.

**Comment by jsvd** [comment]
these don't seem related to the http input plugin, please reopen the issue in the corresponding repositories (or in elastic/logstash when in doubt)

**Comment by QinXiao2017** [comment]
I'm sorry, and thanks.
