### ISSUE TITLE
Logstash HTTP input plugin hangs with large amount connections in WAIT_CLOSE status

### ISSUE THREAD

**Issue by tishion** [logstash-plugins/logstash-input-http#74]
we have 3 Logsasth instances with HTTP input plugin running on port 9600. All of the three instances will hang with large amount connections in WAIT_CLOSE status after several days running. Any suggestions to locate the problem?

Logstash 5.6.1

**Comment by jsvd** [comment]
PR #73 is being worked on to solve this issue.

Currently the http input is built on the Puma web server and it assumes that there aren't many data producers and they keep open connections to logstash.

If your data producers open a connection, send a request and close it again, this can use a lot of file descriptors if logstash exerting backpressure.

If you can, try to reuse connections at the client level connecting to logstash.

**Comment by tishion** [comment]
Thanks a lot @jsvd ! That is pretty good. We can leave this issue now and just wait for the new release. Would you mind my closing this issue?

**Comment by jsvd** [comment]
I'm ok with keeping it open and closing it when #73 is implemented

**Comment by tishion** [comment]
OK thanks again.

**Comment by alanwevans** [comment]
I can confirm this as well and perhaps add a bit more information.

We have a client that sends one log message per http connection.  The client queues up messages so if LS gets behind and a queue builds the client naturally opens the flood gates when LS is back.

We have observed:

- The logstash home (/var/lib/logstash) starts accumulating messages
- With the default heap eventually LS runs out of memory, JVM gives OOM (heap analyzer showed ~ 900 threads at that time)
- With 8G heap LS runs out of file descriptors "Too Many Open files" from the OS (ulimit -n) before OOM
- The LS process shows ~1038-1040 threads (we have the http input set to a max of 1000)
- After the LS process hits ~1038 threads file descriptors start accumulating in the process, puma* files in /var/lib/logstash
- Once the JVM OOMs or hits "Too Many Open files" LS becomes entirely unresponsive, the http status api doesn't respond, the process can't be termed it has to be killed w/ SIGKILL
- Increasing ulimit -n just delays things

I started poking around at the http input plugin.  There is no real logging, no debugging in particular.  I hacked in my own to try to debug.  But maybe it would be worth adding some debug log messages in input-http.

**Comment by jsvd** [comment]
this should no longer happen with #75, released in [version 3.0.8](https://github.com/logstash-plugins/logstash-input-http/blob/master/CHANGELOG.md#308)

**Comment by tishion** [comment]
Thanks @jsvd  will give feedback after several days monitoring.

**Comment by JathinSanghvi** [comment]
@jsvd  - we are using LS 5.1.1 and are facing this issue.. can i just install http-input-plugin or i will need to upgrade LS to some other 5.x or 6.x version? basically question is that if fix will work in older LS?
