### ISSUE TITLE
Respond with ElasticSearch response

### ISSUE THREAD

**Issue by ayZagen** [logstash-plugins/logstash-input-http#90]
If logstash couldn't index to elasticsearch it returns 200 and "ok". 
It should return elasticsearch response. Is it possible ?

For ex: try to send a log with the index name contains any uppercase letter. Logstash will successfully get the log however ElasticSearch will respond  as `Couldn't index event to Elasticsearch, {:status=>400 .... reason => "Invalid index name ..."`

**Comment by magnusbaeck** [comment]
This doesn't seem in any way related to the http input plugin.

**Comment by ayZagen** [comment]
@magnusbaeck  Does the response not generated from plugin ?

**Comment by magnusbaeck** [comment]
No, this plugin has nothing to do with the code that sends events to Elasticsearch. It's the logstash-output-elasticsearch plugin that does that.

I'm quite sure that Logstash _does_ log 400 errors from ES, so I suggest you instead ask a question https://discuss.elastic.co/c/logstash/ to get the matter sorted out.
