### ISSUE TITLE
How can I use logstash-input-http 3.2.0 on logstash 6.x?

### ISSUE THREAD

**Issue by only-gale** [logstash-plugins/logstash-input-http#92]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 3.2.0
- Operating System: x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

Because logstash-input-http 3.0.10 use Puma as its server, and the backlog is 50. I want to use the lateset version of logstash-input-http, which is 3.2.0 on logstash 6.3.2.

I follow the instruction to install logstash-input-http 3.2.0, then I can get this information:
![image](https://user-images.githubusercontent.com/3478864/43943299-a7fe0b56-9cad-11e8-928d-f9ef4324bdd6.png)

And the logstash's Gemfile:
![image](https://user-images.githubusercontent.com/3478864/43943543-83bbf82e-9cae-11e8-9c87-8c53e13f8a46.png)

My logstash's conf file:
![image](https://user-images.githubusercontent.com/3478864/43943601-b5289dd6-9cae-11e8-8cb9-9e186b26d6c2.png)

You can ignore the filter part.

When I hit `bin/logstash -f conf/logstash-http.conf`, the output is below:
![image](https://user-images.githubusercontent.com/3478864/43943660-e57807e2-9cae-11e8-9b8f-b0c11429dbb8.png)

What went wrong? How can I use logstash-input-http 3.2.0 on logstash 6.x?

**Comment by jsvd** [comment]
you can simply update the plugin:

```
/tmp % tar -zxf logstash-6.3.2.tar.gz
/tmp % cd logstash-6.3.2
/tmp/logstash-6.3.2 % bin/logstash-plugin update logstash-input-http
Updating logstash-input-http
Updated logstash-input-http 3.0.10 to 3.2.2
/tmp/logstash-6.3.2 % bin/logstash -e "input { http { port => 5050 } }"
Sending Logstash's logs to /tmp/logstash-6.3.2/logs which is now configured via log4j2.properties
[2018-09-06T17:35:13,137][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.3.2"}
[2018-09-06T17:35:16,376][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-09-06T17:35:16,769][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x3aac37b2 run>"}
[2018-09-06T17:35:16,786][INFO ][logstash.inputs.http     ] Starting http input listener {:address=>"0.0.0.0:5050", :ssl=>"false"}
[2018-09-06T17:35:16,898][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2018-09-06T17:35:17,245][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
{
      "@version" => "1",
       "headers" => {
              "http_host" => "localhost:5050",
           "request_path" => "/",
         "request_method" => "GET",
           "http_version" => "HTTP/1.1",
            "http_accept" => "*/*",
         "content_length" => "0",
        "http_user_agent" => "curl/7.54.0"
    },
       "message" => "",
          "host" => "0:0:0:0:0:0:0:1",
    "@timestamp" => 2018-09-06T16:35:24.489Z
}
```

If you need offline installation, please following the guide https://www.elastic.co/guide/en/logstash/6.3/offline-plugins.html#building-offline-packs
